// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using UIKit;
using Mobile.Extensions.iOS.Sources;
using Fanword.Poco.Models;

namespace Fanword.iOS
{
	public partial class ShowTeamsViewController : BaseViewController
	{
        public string EventId { get; set; }
		public ShowTeamsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);
            GetData();
        }

		void GetData()
		{
            LoadingScreen.Show();
			var apiTask = new ServiceApi().GetEventTeams(EventId);
			apiTask.HandleError(LoadingScreen);
			apiTask.OnSucess(response =>
			{
                LoadingScreen.Hide();
                var source = new CustomListSource<EventTeam>(response.Result, GetCell, (arg1, arg2) => 70);
				tvTeams.Source = source;
				lblCount.Text = response.Result.Count.ToString();
                tvTeams.ReloadData();
			});
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, EventTeam item)
		{
			var cell = tableView.DequeueReusableCell("EventTeamsCell", indexPath) as EventTeamsCell;
			cell.SetData(item);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
