// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using Mobile.Extensions.iOS.Sources;
using Fanword.Shared;
using Mobile.Extensions.iOS.Extensions;
using Fanword.iOS.Shared;

namespace Fanword.iOS
{
	public partial class TeamProfileAboutViewController : BaseViewController
	{
        CustomListSource<AthleteItem> source;
        public string TeamId;
        TeamProfile profile;
		public TeamProfileAboutViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			btnTwitter.Superview.Hidden = true;
			btnFacebook.Superview.Hidden = true;
			btnInstagram.Superview.Hidden = true;

            btnAthletes.TouchUpInside += (sender, args) =>
			{
				SetButtons(btnAthletes);
                tvAthletes.Hidden = false;
				vwLinks.Hidden = true;
			};

            btnLinks.TouchUpInside += (sender, e) => 
            {
				SetButtons(btnLinks);
                tvAthletes.Hidden = true;
                vwLinks.Hidden = false;
			};

            GetData();


			btnTwitter.TouchUpInside += (sender, e) => OpenUrl(profile?.TwitterUrl);
			btnFacebook.TouchUpInside += (sender, e) => OpenUrl(profile?.FacebookUrl);
			btnInstagram.TouchUpInside += (sender, e) => OpenUrl(profile?.InstagramUrl);
			btnWebsite.TouchUpInside += (sender, e) => OpenUrl(profile?.WebsiteUrl);
			btnSchedule.TouchUpInside += (sender, e) => OpenUrl(profile?.ScheduleUrl);
			btnRoster.TouchUpInside += (sender, e) => OpenUrl(profile?.RosterUrl);
		}

        void GetData()
        {
            var apiTask = new ServiceApi().GetAthletesForTeam(TeamId);
            apiTask.HandleError(LoadingScreen);
            apiTask.OnSucess(response =>
            {
                source = new CustomListSource<AthleteItem>(response.Result, GetCell, (tableView, indexPath) => 70);
                source.NoContentText = "No Athletes";
                tvAthletes.Source = source;
                tvAthletes.ReloadData();
            });
        }

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, AthleteItem item)
		{
			var cell = tableView.DequeueReusableCell("TeamAthleteCell", indexPath) as TeamAthleteCell;
            cell.SetData(item, indexPath.Row, (pos, btnFollow) =>
            {
                var model = source.Items[pos];
                Shared.Follower.ToggleFollow(btnFollow, model, model.Id, FeedType.User);
            }, NavigationController);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}

		void SetButtons(UIButton button)
		{
			btnAthletes.SetTitleColor(UIColor.FromRGB(144, 144, 144), UIControlState.Normal);
            btnLinks.SetTitleColor(UIColor.FromRGB(144, 144, 144), UIControlState.Normal);
            button.SetTitleColor(UIColor.FromRGB(21, 21, 21), UIControlState.Normal);
		}

		public void SetView(TeamProfile profile)
		{

            this.profile = profile;
			if (!string.IsNullOrEmpty(profile.TwitterUrl))
			{
				btnTwitter.Superview.Hidden = false;
			}
			if (!string.IsNullOrEmpty(profile.FacebookUrl))
			{
				btnFacebook.Superview.Hidden = false;
			}
			if (!string.IsNullOrEmpty(profile.InstagramUrl))
			{
				btnInstagram.Superview.Hidden = false;
			}

		}

		void OpenUrl(string link)
		{
            if (string.IsNullOrEmpty(link))
                return;
			try
			{
				if (!link.ToLower().StartsWith("http"))
				{
					link = "http://" + link;
				}
				UIApplication.SharedApplication.OpenUrl(new NSUrl(link));
			}
			catch { }
		}
	}
}
