// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using System.Collections.Generic;
using Mobile.Extensions.iOS.Sources;

namespace Fanword.iOS
{
    public partial class FavoriteViewController : UIViewController
    {
        CustomListSource<FavoriteItem> source;
        public FavoriteViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            tvFavorites.EstimatedRowHeight = 60;
        }

        public void SetData(List<FavoriteItem> favorites)
        {
            source = new CustomListSource<FavoriteItem>(favorites, GetCell,(arg1, arg2) => UITableView.AutomaticDimension);
            source.NoContentText = "No Content";
            tvFavorites.Source = source;
            tvFavorites.ReloadData();
        }

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, FavoriteItem item)
		{
			var cell = tableView.DequeueReusableCell("FavoriteCell", indexPath) as FavoriteCell;
			cell.SetData(item, NavigationController);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
