// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using UIKit;
using Mobile.Extensions.iOS.Sources;
using Fanword.Shared.Models;
using Fanword.iOS.Shared;

namespace Fanword.iOS
{
    public partial class NotificationsViewController : BaseViewController
    {
        UIRefreshControl refreshControl;
        CustomListSource<UserNotification> source;
        public NotificationsViewController(IntPtr handle) : base(handle)
        {
        }

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            tvNotifications.EstimatedRowHeight = 60;
            btnBack.TouchUpInside += (sender, e) => 
            {
                NavigationController.PopViewController(true);
            };

            GetData();

			refreshControl = new UIRefreshControl();
			tvNotifications.AddSubview(refreshControl);
			refreshControl.AddTarget((sender, e) => GetData(), UIControlEvent.ValueChanged);
			if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
			{
				tvNotifications.RefreshControl = refreshControl;
			}
        }

        void GetData()
        {
            var apiTask = new ServiceApi().GetNotifcations();
            apiTask.HandleError();
            apiTask.OnSucess((response) =>
            {
                source = new CustomListSource<UserNotification>(response.Result, GetCell,(arg1, arg2) => UITableView.AutomaticDimension);
                source.ItemClick += (sender, e) => 
                {
                    Navigator.HandleNotificationTap(NavigationController, e.MetaData, e.Title, e.Message);
                };

                tvNotifications.Source = source;
                tvNotifications.ReloadData();
                refreshControl.EndRefreshing();
				var apiTask2 = new ServiceApi().MarkNotificationsAsRead();
				apiTask2.HandleError();
			});
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, UserNotification item)
		{
            var cell = tableView.DequeueReusableCell("NotificationCell", indexPath) as NotificationCell;
			cell.SetData(item, NavigationController);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
