// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Extensions;

namespace Fanword.iOS
{
	public partial class SettingsViewController : BaseViewController
	{
		public SettingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);

            vwBasicProfile.AddGestureRecognizer(new UITapGestureRecognizer(() =>
            {
                var controller = Storyboard.InstantiateViewController<BasicInfoViewContoller>();
                NavigationController.PushViewController(controller, true);
            }));

			vwStudenAthlete.AddGestureRecognizer(new UITapGestureRecognizer(() =>
			{
				var controller = Storyboard.InstantiateViewController<StudentAthleteInfoViewController>();
				NavigationController.PushViewController(controller, true);
			}));
        }
	}
}
