// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using Mobile.Extensions.iOS.Extensions;
using Fanword.Shared;
using Fanword.Shared.Helpers;
using Fanword.iOS.Shared;
using FFImageLoading;
using Plugin.Dialog;
using CoreGraphics;
using Plugin.Settings;

namespace Fanword.iOS
{
	public partial class TeamProfileViewController : BaseViewController
	{
		public string TeamId;
		FeedViewController feedController;
		TeamProfileAboutViewController aboutController;
        TeamProfileRankingsViewController rankingsController;
        ScoresViewController scoresController;
		TeamProfile profile;
		public bool GoToRankings;
		public TeamProfileViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}


		public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ShowHelpIfNecessary(TutorialHelper.Profiles);

			btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);
			feedController = Storyboard.InstantiateViewController<FeedViewController>();
			feedController.HeaderView = vwHeader;
			feedController.Id = TeamId;
			feedController.Type = FeedType.Team;
			feedController.RefreshStarted += (sender, e) => GetData();
			AddChildViewController(feedController);
			AddToScrollView(feedController.View, 0);
			feedController.HideAddPost();

            scoresController = Storyboard.InstantiateViewController<ScoresViewController>();
            scoresController.TeamId = TeamId;
            AddToScrollView(scoresController.View, 1);
            scoresController.HideFilter();
			AddChildViewController(scoresController);

			rankingsController = Storyboard.InstantiateViewController<TeamProfileRankingsViewController>();
            rankingsController.TeamId = TeamId;
            AddToScrollView(rankingsController.View, 2);
			AddChildViewController(rankingsController);

			aboutController = Storyboard.InstantiateViewController<TeamProfileAboutViewController>();
            aboutController.TeamId = TeamId;
			AddToScrollView(aboutController.View, 3);
			AddChildViewController(aboutController);

			svScroller.ContentSize = new CoreGraphics.CGSize() { Width = UIScreen.MainScreen.Bounds.Width * 4 };

			svScroller.Scrolled += (sender, e) =>
			{
				lcIndicatorLeading.Constant = svScroller.ContentOffset.X / 4f;
				int position = (int)(svScroller.ContentOffset.X / UIScreen.MainScreen.Bounds.Width);
				if (svScroller.ContentOffset.X % UIScreen.MainScreen.Bounds.Width > (UIScreen.MainScreen.Bounds.Width / 2f))
				{
					position++;
				}

				if (position == 1)
				{
					ShowHelpIfNecessary(TutorialHelper.SchedulesScores);
				}
			};

			GetData();

			btnProfile.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint(), true);
			};
            btnScores.TouchUpInside += (sender, e) => 
            {
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width }, true);
            };
            btnRankings.TouchUpInside += (sender, e) => 
            {
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 2 }, true);
            };
			btnAbout.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 3 }, true);
			};

			btnFollow.TouchUpInside += (sender, e) =>
			{
                if (profile == null)
                    return;

                Shared.Follower.ToggleFollow(btnFollow, profile, profile.Id, FeedType.Team, (following) =>
				{
					GetData();
				});
			};

			btnAdmin.TouchUpInside += (sender, e) =>
			{
                if (profile == null)
                    return;

                var controller = Storyboard.InstantiateViewController<AdminInformationViewController>();
                controller.Id = TeamId;
                controller.Type = FeedType.Team;
                controller.IsAdmin = profile.IsProfileAdmin;
                NavigationController.PushViewController(controller, true);

			};

			lblTitle.AddGestureRecognizer(new UITapGestureRecognizer(() =>
			{
				var controller = Storyboard.InstantiateViewController<SchoolProfileViewController>();
				controller.SchoolId = profile.SchoolId;
				NavigationController.PushViewController(controller, true);
			}));

			if (GoToRankings)
			{
				svScroller.SetContentOffset(new CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 2 }, false);
			}

            lblFollowers.Superview.AddGestureRecognizer(new UITapGestureRecognizer(() => 
            {
                if (profile == null)
                    return;
                var controller = Storyboard.InstantiateViewController<FollowersViewController>();
                controller.Id = profile.Id;
                controller.Type = FeedType.Team;
                NavigationController.PushViewController(controller, true);
            }));

		}

        void AddToScrollView(UIView view, int position)
        {
			svScroller.Add(view);
			var frame = view.Frame;
            frame.Y = 0;
			frame.X = UIScreen.MainScreen.Bounds.Width * position;
			frame.Height = UIScreen.MainScreen.Bounds.Height - 120;
			frame.Width = UIScreen.MainScreen.Bounds.Width;
			view.Frame = frame;
        }

        public override void ViewDidLayoutSubviews()
        {
            base.ViewDidLayoutSubviews();
            FixFrame(feedController.View);
			FixFrame(aboutController.View);
			FixFrame(scoresController.View);
			FixFrame(rankingsController.View);
 		} 

        void FixFrame (UIView view)
        {
            var f = view.Frame;
            f.Width = UIScreen.MainScreen.Bounds.Width;
            f.Height = UIScreen.MainScreen.Bounds.Height - 120;
            view.Frame = f;
        }

		void GetData()
		{
			var apiTask = new ServiceApi().GetTeamProfile(TeamId);
			apiTask.HandleError();
			apiTask.OnSucess(response =>
			{
				profile = response.Result;
				aboutController.SetView(profile);
                rankingsController.SetView(profile);
                lblTitle.UserInteractionEnabled = true;

				lblName.Text = response.Result.SchoolName;
				lblTitle.Text = response.Result.SchoolName;
                lblSport.Text = response.Result.SportName;
                lblBottomSport.Text = response.Result.SportName;

				lblPosts.Text = LargeValueHelper.GetString(response.Result.Posts);
				lblFollowers.Text = LargeValueHelper.GetString(response.Result.Followers);
                lblRecord.Text = $"{profile.Wins}W {profile.Loss}L {profile.Ties}T";
                lblRanking.Text = profile.Ranking;

				var color = ColorHelper.GetColor(profile.PrimaryColor, btnBack.Superview.BackgroundColor);
				btnBack.Superview.BackgroundColor = color;
				btnProfile.Superview.Superview.BackgroundColor = color;

				//btnAdmin.SetTitle("Become an Admin of this profile", UIControlState.Normal);
				Views.SetFollowed(btnFollow, response.Result.IsFollowing);

				if (!string.IsNullOrEmpty(response.Result.ProfileUrl))
				{
					ImageService.Instance.LoadUrl(response.Result.ProfileUrl).Retry(3, 300).Into(imgProfile);
				}

				if (profile.IsProfileAdmin)
				{
                    btnAdmin.SetTitle("You are an admin of this profile", UIControlState.Normal);
				}
			});
		}
	}
}
