// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Extensions;
using Fanword.Shared;
using Fanword.Poco.Models;
using Facebook.LoginKit;
using CoreGraphics;
using Facebook.CoreKit;
using FFImageLoading.Transformations;
using CoreText;
using MixpanelLib;

namespace Fanword.iOS
{
	public partial class LoginViewController : BaseViewController
	{
		LoginButton FacebookButton;

		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

        public override UIStatusBarStyle PreferredStatusBarStyle ()
		{
			return UIStatusBarStyle.LightContent;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

            FacebookButton = new LoginButton (new CGRect (0, 0, vwFacebookContainer.Frame.Width, vwFacebookContainer.Frame.Height));
			FacebookButton.LoginBehavior = LoginBehavior.SystemAccount;
			FacebookButton.Layer.CornerRadius = 10;
			FacebookButton.ClipsToBounds = true;
			FacebookButton.SetImage (null, UIControlState.Normal);
			FacebookButton.ContentEdgeInsets = new UIEdgeInsets (0, 0, 0, 0);
			FacebookButton.ReadPermissions = new [] { "email", "public_profile", "user_friends" };
            FacebookButton.SetAttributedTitle (new NSAttributedString (" ") , UIControlState.Normal);
			FacebookButton.Completed += (sender, e) =>
			{
				if (e.Error != null)
				{

				}
				else if (!e.Result.IsCancelled)
				{
					LoadingScreen.Show ();

					var apiTask = new ServiceApi ().RegisterFacebook (e.Result.Token.TokenString);
					apiTask.HandleError (LoadingScreen);
					apiTask.OnSucess ((response) =>
					{
                        LoadingScreen.Hide();
						var main = Storyboard.InstantiateViewController ("MainViewController") as MainViewController;
						NavigationController.PushViewController (main, true);
					});
				}
			};
			vwFacebookContainer.InsertSubview (FacebookButton,0);

#if DEBUG
			//txtEmail.Text = "jacob.krings@agilx.com";
            txtEmail.Text = "support@agilx.com";
			txtPassword.Text = "Password$1";
#endif

			//btnRegister.TouchUpInside += (sender, e) =>
			//{
			//	var controller = Storyboard.InstantiateViewController<SignUpViewController> ();
			//	NavigationController.PushViewController (controller, true);
			//};

			btnSignIn.TouchUpInside += (sender, e) =>
			{
                Mixpanel.SharedInstance.Track("SignIn");

				LoadingScreen.Show ();
				var apiTask = new ServiceApi ().Login (txtEmail.Text, txtPassword.Text);
				apiTask.HandleError (LoadingScreen);
				apiTask.OnSucess ((result) =>
				{
					LoadingScreen.Hide ();
					var controller = Storyboard.InstantiateViewController<MainViewController> ();
					NavigationController.PushViewController (controller, true);
				});
			};

			btnForgotPassword.TouchUpInside += (sender, e) =>
			{
				var controller = Storyboard.InstantiateViewController<ForgotPasswordViewController> ();
				NavigationController.PushViewController (controller, true);
			};

			if (LocalStorage.IsLoggedIn ())
			{
				var controller = Storyboard.InstantiateViewController<MainViewController> ();
				NavigationController.PushViewController (controller, false);
			}

		}
	}
}
