// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using UIKit;
using Mobile.Extensions.iOS.Sources;
using Fanword.Poco.Models;
using System.Linq;
using Fanword.iOS.Shared;

namespace Fanword.iOS
{
	public partial class SportRankingsViewController : BaseViewController
	{
		public string SportId;
        CustomListSource<Ranking> source;
		public SportRankingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
			var apiTask = new ServiceApi().GetSportRankings(SportId);
			apiTask.HandleError(LoadingScreen);
			apiTask.OnSucess(response =>
			{
                source = new CustomListSource<Ranking>(response.Result, GetCell,(arg1, arg2) => 70 );
				lblDate.Text = response.Result.FirstOrDefault()?.DateUpdatedUtc.ToLocalTime().ToString("D");
				tvRankings.Source = source;
                tvRankings.ReloadData();
			});
        }

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, Ranking item)
		{
			var cell = tableView.DequeueReusableCell("SportRankingCell", indexPath) as SportRankingCell;
			cell.SetData(item, indexPath.Row, (pos, btnFollow) =>
			{
				var model = source.Items[pos];
			    Shared.Follower.ToggleFollow(btnFollow, model, model.TeamId, FeedType.Team);
			}, NavigationController);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
