// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Xamarin;

namespace Fanword.iOS
{
	public partial class PreviousNexView : IQPreviousNextView
	{
		public PreviousNexView (IntPtr handle) : base (handle)
		{
		}

	}
}
