// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Poco.Models;
using Fanword.Shared;
using FFImageLoading;
using FFImageLoading.Transformations;
using Foundation;
using Mobile.Extensions.Extensions;
using Mobile.Extensions.iOS.Extensions;
using Plugin.Settings;
using UIKit;

namespace Fanword.iOS
{
	public partial class StudentAthleteInfoViewController : BaseViewController
	{
		public StudentAthleteInfoViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);

			btnEdit.TouchUpInside += (sender, args) =>
			{
                var controller = Storyboard.InstantiateViewController<OnboardingAthleteTeamViewController>();
                controller.IsEdit = true;
                NavigationController.PushViewController(controller, true);
			};

			btnDelete.TouchUpInside += (sender, args) =>
			{
                LoadingScreen.Show();
				var apiTask = new ServiceApi().DeleteAthlete();
				apiTask.HandleError();
				apiTask.OnSucess((response) =>
				{
                    LoadingScreen.Hide();
					svAthlete.Hidden = true;
					btnEdit.SetTitle("Add", UIControlState.Normal);
					btnDelete.Superview.Hidden = true;
				});
			};
		}

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

			var user = CrossSettings.Current.GetValueOrDefaultJson<User>("User");

			if (string.IsNullOrEmpty(user.AthleteTeamId))
			{
                svAthlete.Hidden = true;
                btnEdit.SetTitle("Add", UIControlState.Normal);
                btnDelete.Superview.Hidden = true;
			}
			else
			{
				svAthlete.Hidden = false;
				btnEdit.SetTitle("Edit", UIControlState.Normal);
                btnDelete.Superview.Hidden = false;
				if (!string.IsNullOrEmpty(user.AthleteProfileUrl))
					ImageService.Instance.LoadUrl(user.AthleteProfileUrl).Retry(3, 300).Transform(new CircleTransformation()).Into(imgProfile);

				lblSchoolName.Text = user.AthleteSchool;
				lblSportName.Text = user.AthleteSport;
				lblYears.Text = user.AthleteStartDateUtc.Year + " - " + (user.AthleteEndDateUtc != null ? user.AthleteEndDateUtc?.Year.ToString() : "Present");
			}

        }

	}
}
