// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Fanword.Poco.Models;
using Foundation;
using Mobile.Extensions.iOS.Sources;
using UIKit;

namespace Fanword.iOS
{
	public partial class FavoriteUsersViewController : UIViewController
	{
		CustomListSource<FavoriteItem> source;
        List<FavoriteItem> Followers;
        List<FavoriteItem> Following;
		public FavoriteUsersViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			tvFavorites.EstimatedRowHeight = 60;

			btnFollowers.TouchUpInside += (sender, e) =>
			{
                ShowFollowers();
			};

			btnFollowing.TouchUpInside += (sender, e) =>
			{
                ShowFollowing();
			};
			SetButtons(btnFollowing);
		}

		void SetButtons(UIButton button)
		{
            btnFollowers.SetTitleColor(UIColor.FromRGB(144, 144, 144), UIControlState.Normal);
            btnFollowing.SetTitleColor(UIColor.FromRGB(144, 144, 144), UIControlState.Normal);
			button.SetTitleColor(UIColor.FromRGB(21, 21, 21), UIControlState.Normal);
		}

        public void ShowFollowers()
        {
			SetButtons(btnFollowers);
			source.Items = Followers;
			tvFavorites.ReloadData();
        }

        public void ShowFollowing()
        {
			SetButtons(btnFollowing);
			source.Items = Following;
			tvFavorites.ReloadData();
        }

		public void SetData(List<FavoriteItem> following, List<FavoriteItem> followers)
		{
            Following = following;
            Followers = followers;

			source = new CustomListSource<FavoriteItem>(Following, GetCell, (arg1, arg2) => UITableView.AutomaticDimension);
			source.NoContentText = "No Content";
			tvFavorites.Source = source;
			tvFavorites.ReloadData();
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, FavoriteItem item)
		{
			var cell = tableView.DequeueReusableCell("FavoriteCell", indexPath) as FavoriteCell;
			cell.SetData(item, NavigationController);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
