// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.iOS.Shared;
using Fanword.Poco.Models;
using Fanword.Shared;
using System.Diagnostics;

namespace Fanword.iOS
{
	public partial class ShareOptionsViewController : BaseViewController
	{
        public Post post;
        public BaseViewController Parent;
        public LoadingScreenViewController ParentLoadingScreen;
        public FeedTableView FeedTable;
		public ShareOptionsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
			View.BackgroundColor = UIColor.Clear;
			vwBackground.AddGestureRecognizer(new UITapGestureRecognizer(() => DismissViewController(true, null)));

			btnFacebook.TouchUpInside += async (sender, e) =>
			{
				DismissViewController(true, null);
                await Sharer.ShareFacebook(Parent, post);
                var apiTask = new ServiceApi().SaveShare(post.Id);
			};

            btnFanword.TouchUpInside += async (sender, e) => 
            {
                DismissViewController(true, null);
                await Sharer.ShareFanword(post);
                FeedTable.GetNewsFeedData(true);
            };

			btnOther.TouchUpInside += async (sender, e) =>
			{
                Debugger.Break();
				DismissViewController(true, null);
                ParentLoadingScreen.Show();
                await Sharer.ShareOther(Parent, post,() => 
                {
                    var apiTask = new ServiceApi().SaveShare(post.Id);  
                });
                ParentLoadingScreen.Hide();
			};
        }
	}
}
