// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using UIKit;
using Mobile.Extensions.iOS.Sources;
using Fanword.Poco.Models;

namespace Fanword.iOS
{
	public partial class TeamProfileRankingsViewController : BaseViewController
	{
        public string TeamId;
        CustomListSource<TeamRanking> source;
        TeamProfile profile;
		public TeamProfileRankingsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			var apiTask = new ServiceApi().GetTeamRankings(TeamId);
            apiTask.HandleError(LoadingScreen);
			apiTask.OnSucess((response) =>
			{
                source = new CustomListSource<TeamRanking>(response.Result, GetCell, (arg1, arg2) => 40);
                source.NoContentText = "No Rankings";
			    tvRankings.Source = source;
                tvRankings.ReloadData();
			});

			btnRankings.TouchUpInside += (sender, e) =>
			{
                if (profile == null)
                    return;
                
				var controller = Storyboard.InstantiateViewController<SportProfileViewController>();
                controller.SportId = profile.SportId;
                controller.GoToRankings = true;
                NavigationController.PushViewController(controller, true);
			};
        }

        public void SetView(TeamProfile profile)
        {
            this.profile = profile;
            lblRecord.Text = profile.Wins + "W " + profile.Loss + "L " + profile.Ties + "T";
            btnRankings.SetTitle("Check the latest " + profile.SportName + " rankings", UIControlState.Normal);
        }

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, TeamRanking item)
		{
			var cell = tableView.DequeueReusableCell("TeamRankingCell", indexPath) as TeamRankingCell;
            cell.SetData(item, source.Items, indexPath.Row);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
