// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MediaPlayer;
using UIKit;

namespace Fanword.iOS
{
	public partial class ViewVideoViewController : MPMoviePlayerViewController
	{
		public NSUrl Url;
		public ViewVideoViewController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);
			if (MoviePlayer != null)
			{
				MoviePlayer.SourceType = MPMovieSourceType.Streaming;
				MoviePlayer.ContentUrl = Url;
				MoviePlayer.Play();
			}
		}

		public override bool ShouldAutorotate()
		{
			return true;
		}

		public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations()
		{
			return UIInterfaceOrientationMask.Portrait | UIInterfaceOrientationMask.Landscape;
		}

		public override UIInterfaceOrientation InterfaceOrientation
		{
			get
			{
				var b = base.InterfaceOrientation;
				return b;
			}
		}
	}
}
