// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Fanword.Poco.Models;
using Fanword.Shared;
using Fanword.Shared.Helpers;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using Plugin.Dialog;
using UIKit;

namespace Fanword.iOS
{
	public partial class AdminInformationViewController : BaseViewController
	{
		public string Id;
		public FeedType Type;
		public bool IsAdmin;
		public AdminInformationViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			//ShowHelpIfNecessary(TutorialHelper.BecomeAdmin);
            btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);

			if (IsAdmin)
			{
                btnNext.Hidden = true;
			}

            btnNext.TouchUpInside += (sender, e) => NextClicked();

            btnContact.TouchUpInside += (sender, e) => 
            {
                UIApplication.SharedApplication.OpenUrl(new NSUrl("mailto:"+ FanwordConstants.Email));
            };
        }

		void NextClicked()
		{
			if (!IsAdmin)
			{
				LoadingScreen.Show();
				Task apiTask = null;

				if (Type == FeedType.School)
					apiTask = new ServiceApi().RequestSchoolAdmin(Id);
				else
					apiTask = new ServiceApi().RequestTeamAdmin(Id);

				apiTask.HandleError(LoadingScreen);
				apiTask.OnSucess(response =>
				{
					LoadingScreen.Hide();
					CrossDialog.Current.Show("Request Sent", "You must be approved by an administrator. Check back later to see if you've been approved.");
				});
			}
		}
	}
}
