// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared.Models;
using Foundation;
using UIKit;

namespace Fanword.iOS
{
    public partial class AdminCell : UITableViewCell
    {
		ImageLoaderHelper imageTask;
        bool IsNew = true;
        PostAsAdminProfile model;
        public AdminCell(IntPtr handle) : base(handle)
        {
        }

		public void SetData(PostAsAdminProfile item, Action<PostAsAdminProfile> itemClicked)
		{
            if(IsNew)
            {
                UserInteractionEnabled = true;
                AddGestureRecognizer(new UITapGestureRecognizer((obj) => 
                {
                    itemClicked?.Invoke(model);  
                }));
                IsNew = false;
            }
            model = item;
			lblTitle.Text = item.Title;
            lblSubtitle.Text = item.SubTitle;

			imageTask?.Cancel(item.Url);
			if (!string.IsNullOrEmpty(item.Url))
			{
				imageTask = new ImageLoaderHelper(item.Url, imgProfile, "DefaultProfile");
			}
		}
	}
}
