// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using FFImageLoading;
using FFImageLoading.Work;

namespace Fanword.iOS
{
	public partial class AthleteTeamCell : UITableViewCell
	{
		ImageLoaderHelper imageTask;

		public AthleteTeamCell (IntPtr handle) : base (handle)
		{
		}

		public void SetData (AthleteTeam item)
		{
			lblSport.Text = item.SportName;
			lblSchool.Text = item.SchoolName;

			imageTask?.Cancel (item.ProfilePublicUrl);
			if (!string.IsNullOrEmpty (item.ProfilePublicUrl))
			{
				imageTask = new ImageLoaderHelper (item.ProfilePublicUrl, imgProfile, "DefaultProfile");
			}
		}
	}
}
