// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Fanword.iOS
{
	public partial class DateCell : UICollectionViewCell
	{
		public DateCell (IntPtr handle) : base (handle)
		{
		}

        public void SetData(DateTime item, DateTime currentDate)
        {
            if(item == DateTime.Now.Date.ToUniversalTime())
            {
                lblDate.Text = "Today";   
            }
            else
            {
				lblDate.Text = item.ToLocalTime().ToString("M");
            }

            if(item == currentDate)
            {
                BackgroundColor = UIColor.FromRGB(244, 244, 244);
                lblDate.TextColor = UIColor.Black;
            }
            else
            {
                BackgroundColor = UIColor.White;
				lblDate.TextColor = UIColor.FromRGB(144,144,144);
            }
        }
	}
}
