// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Poco.Models;
using Foundation;
using UIKit;
using FFImageLoading.Transformations;

namespace Fanword.iOS
{
	public partial class LikeCell : UITableViewCell
	{
		ImageLoaderHelper imageTask;
		public LikeCell (IntPtr handle) : base (handle)
		{
		}

		public void SetData (PostLike item)
		{
			lblName.Text = item.Username;
			imageTask?.Cancel (item.ProfileUrl);
			if (!string.IsNullOrEmpty (item.ProfileUrl))
			{
				imageTask = new ImageLoaderHelper (item.ProfileUrl, imgProfile, "DefaultProfile", null, new CircleTransformation());
			}
		}
	}
}
