// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared.Models;
using Foundation;
using UIKit;

namespace Fanword.iOS
{
	public partial class MenuHeaderCell : UITableViewCell
	{
		public MenuHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public void SetData(MenuItem item)
		{
            lblTitle.Text = item.Title;			
		}
	}
}
