// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Shared.Models;
using FFImageLoading.Transformations;
using Fanword.Shared;

namespace Fanword.iOS
{
	public partial class NotificationCell : UITableViewCell
	{
        UINavigationController navigationController;
        bool IsNew = true;
        UserNotification model;
		ImageLoaderHelper imageTask;
		public NotificationCell (IntPtr handle) : base (handle)
		{
		}

		public void SetData(UserNotification item, UINavigationController navigationController)
		{
			this.navigationController = navigationController;
			model = item;
			if (IsNew)
            {

				IsNew = false;
			}
            lblTitle.Text = item.Title;
			
            vwIsNew.Hidden = item.IsRead;

			lblTimeAgo.Text = TimeAgoHelper.GetTimeAgo(item.DateCreatedUtc);

			imageTask?.Cancel(item.ProfileUrl);
			if (!string.IsNullOrEmpty(item.ProfileUrl))
			{
				imageTask = new ImageLoaderHelper(item.ProfileUrl, imgProfile, "DefaultProfile", null, new CircleTransformation());
			}
		}
	}
}
