// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using FFImageLoading.Transformations;

namespace Fanword.iOS
{
	public partial class PostShareCell : UITableViewCell
	{
        ImageLoaderHelper imageTask;
		public PostShareCell (IntPtr handle) : base (handle)
		{
		}
		
		public void SetData(PostShare item)
		{
            lblName.Text = item.FirstName + " " + item.LastName;
			imageTask?.Cancel(item.ProfileUrl);
			if (!string.IsNullOrEmpty(item.ProfileUrl))
			{
				imageTask = new ImageLoaderHelper(item.ProfileUrl, imgProfile, "DefaultProfile", null, new CircleTransformation());
			}
		}
	}
}
