// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using FFImageLoading.Transformations;

namespace Fanword.iOS
{
	public partial class PostTagCell : UITableViewCell
	{
		ImageLoaderHelper imageTask;
		public PostTagCell (IntPtr handle) : base (handle)
		{
		}

		public void SetData(PostTag item)
		{
            lblTitle.Text = item.Title;
            lblSubtitle.Text = item.Subtitle;
            lblSubtitle.Hidden = string.IsNullOrEmpty(item.Subtitle);
			imageTask?.Cancel(item.ProfileUrl);
			if (!string.IsNullOrEmpty(item.ProfileUrl))
			{
				imageTask = new ImageLoaderHelper(item.ProfileUrl, imgProfile, "DefaultProfile", null, new CircleTransformation());
			}
		}
	}
}
