// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using System.Collections.Generic;

namespace Fanword.iOS
{
	public partial class ProfileSearchCell : UITableViewCell
	{
		ImageLoaderHelper imageTask;
		public ProfileSearchCell (IntPtr handle) : base (handle)
		{
		}

        public void SetData(Profile item, List<string> schools, List<string> teams, List<string> sports)
        {
            lblTitle.Text = item.Name;

            lblSubTitle.Hidden = string.IsNullOrEmpty(item.SubTitle);
            lblSubTitle.Text = item.SubTitle ?? "";


            if(schools.Contains(item.Id) || teams.Contains(item.Id) || sports.Contains(item.Id))
            {
                imgTagged.Image = UIImage.FromBundle("IconChecked");
            }
            else
            {
                imgTagged.Image = UIImage.FromBundle("IconUnchecked");
            }

			imageTask?.Cancel(item.ProfilePublicUrl);
			if (!string.IsNullOrEmpty(item.ProfilePublicUrl))
			{
				imageTask = new ImageLoaderHelper(item.ProfilePublicUrl, imgProfile, "DefaultProfile");
			}
        }
	}
}
