// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Fanword.Poco.Models;
using Foundation;
using UIKit;

namespace Fanword.iOS
{
	public partial class TeamRankingCell : UITableViewCell
	{
		public TeamRankingCell (IntPtr handle) : base (handle)
		{
		}

        public void SetData(TeamRanking item, List<TeamRanking> items, int position)
        {
			lblDate.Text = item.DateUpdatedUtc.ToString("dd MMMM");
			lblRank.Text = item.Rank.ToString();

			if (position == items.Count - 1)
			{
                lblChange.Hidden = true;
                imgChange.Hidden = true;
			}
			else
			{
                lblChange.Hidden = false;
                imgChange.Hidden = false;
				var nextItem = items[position + 1];
				var change = nextItem.Rank - item.Rank;
				if (change < 0)
				{
                    lblChange.TextColor = UIColor.Red;
				}
				else
				{
					lblChange.TextColor = UIColor.FromRGB(0, 160, 0);
				}

				lblChange.Text = Math.Abs(change).ToString();
			}
        }
	}
}
