// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using Fanword.iOS.Shared;
using FFImageLoading.Transformations;

namespace Fanword.iOS
{
	public partial class TeamAthleteCell : UITableViewCell
	{
        bool isNew = true;
        int pos;
		ImageLoaderHelper imageTask;
        AthleteItem item;
		public TeamAthleteCell (IntPtr handle) : base (handle)
		{
		}

        public void SetData(AthleteItem item, int position, Action<int, UIButton> followClicked, UINavigationController navigationController)
        {
            this.item = item;
            pos = position;
            if(isNew)
            {
                btnFollow.TouchUpInside += (sender, e) => 
                {
                    followClicked?.Invoke(pos, btnFollow);
                };

				imgProfile.UserInteractionEnabled = true;
				imgProfile.AddGestureRecognizer(new UITapGestureRecognizer(() =>
				{
					Navigator.GoToUserProfile(navigationController, this.item.Id);
				}));

				lblName.UserInteractionEnabled = true;
				lblName.AddGestureRecognizer(new UITapGestureRecognizer(() =>
				{
					Navigator.GoToUserProfile(navigationController, this.item.Id);
				}));

                isNew = false;
            }
            lblName.Text = item.Name;
            lblTeam.Text = item.SchoolName + " " + item.SportName;

            Views.SetFollowed(btnFollow, item.IsFollowing);

			imageTask?.Cancel(item.ProfileUrl);
			if (!string.IsNullOrEmpty(item.ProfileUrl))
			{
				imageTask = new ImageLoaderHelper(item.ProfileUrl, imgProfile, "DefaultProfile", null, new CircleTransformation());
			}

        }
	}
}
