// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Poco.Models;
using Fanword.Shared;
using Foundation;
using Mobile.Extensions.iOS.Extensions;
using UIKit;
using Mobile.Extensions.iOS.Sources;

namespace Fanword.iOS
{
	public partial class FollowersViewController : BaseViewController
	{
        public string Id;
        public FeedType Type;
        CustomListSource<Follower> source;
		public FollowersViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);
            GetData();
        }

		void GetData()
		{
			LoadingScreen.Show();
			var apiTask = new ServiceApi().Followers(Id, Type);
			apiTask.HandleError(LoadingScreen);
			apiTask.OnSucess((response) =>
			{
                LoadingScreen.Hide();
				lblCount.Text = response.Result.Count.ToString();
                source = new CustomListSource<Follower>(response.Result, GetCell, (arg1, arg2) => 60);
                source.ItemClick += (sender, e) => 
                {
                    Fanword.iOS.Shared.Navigator.GoToUserProfile(NavigationController, e.Id);
                };
                tvFollowers.Source = source;
                tvFollowers.ReloadData();
			});
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, Follower item)
		{
			var cell = tableView.DequeueReusableCell("FollowerCell", indexPath) as FollowerCell;
			cell.SetData(item);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
