// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared;
using Foundation;
using UIKit;
using Fanword.Poco.Models;
using Mobile.Extensions.iOS.Extensions;
using Mobile.Extensions.iOS.Sources;
using Fanword.iOS.Shared;

namespace Fanword.iOS
{
	public partial class PostTagsViewController : UIViewController, IPostDetails
	{
		public string Name => "Tags";
		public int Count { get; set; }
		public string PostId { get; set; }
		public Action<string, int> UpdateParent;

		public PostTagsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			GetData();


		}

		void GetData()
		{
			var apiTask = new ServiceApi().GetTags(PostId);
			apiTask.HandleError();
			apiTask.OnSucess(response =>
		    {
			    var source = new CustomListSource<PostTag>(response.Result, GetCell, (arg1, arg2) => 55);
                source.ItemClick += (sender, e) => 
                {
                    var item = e;
					if (item.Type == FeedType.User)
					{
                        Navigator.GoToUserProfile(NavigationController, item.Id);
					}
					if (item.Type == FeedType.Team)
					{
						Navigator.GoToTeamProfile(NavigationController, item.Id, false);
					}
					if (item.Type == FeedType.School)
					{
						Navigator.GoToSchoolProfile(NavigationController, item.Id, false);
					}
					if (item.Type == FeedType.Sport)
					{
						Navigator.GoToSportProfile(NavigationController, item.Id, false);
					}
                };
			    source.NoContentText = "No Tags";
			    tvTags.Source = source;
			    Count = response.Result.Count;
			    tvTags.ReloadData();
			    UpdateParent?.Invoke(Name, Count);
		   });
		}

		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, PostTag item)
		{
			var cell = tableView.DequeueReusableCell("PostTagCell", indexPath) as PostTagCell;
			cell.SetData(item);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
