// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Interfaces;

namespace Fanword.iOS
{
	public partial class LoadingScreenViewController : UIViewController, ILoadingScreen
	{
		public UIViewController Parent;
		public LoadingScreenViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Perform any additional setup after loading the view, typically from a nib.		
			var b = UIScreen.MainScreen.Bounds;
			View.Frame = b;

		}

		public override void ViewDidLayoutSubviews ()
		{
			base.ViewDidLayoutSubviews ();

			var b = UIScreen.MainScreen.Bounds;
			View.Frame = b;
			//if (_parent.View.Frame.Height < UIScreen.MainScreen.Bounds.Height)
			//{
			//	var f = View.Frame;
			//	f.Height = _parent.View.Frame.Height - (UIScreen.MainScreen.Bounds.Height - _parent.View.Frame.Height);
			//	View.Frame = f;
			//}

		}

		public void SetText (string text)
		{
			lblTitle.Text = text;
		}

		public void Show ()
		{
			//if (_parent.View.Frame.Height < UIScreen.MainScreen.Bounds.Height)
			//{
			//	var f = View.Frame;
			//	f.Height = _parent.View.Frame.Height - (UIScreen.MainScreen.Bounds.Height - _parent.View.Frame.Height);
			//	View.Frame = f;
			//}
			Parent.View.AddSubview (this.View);

			//viewContainer.Layer.CornerRadius = 5;

			Parent.View.BringSubviewToFront (this.View);
			this.View.Layer.Opacity = 0;
			imgImage.Alpha = 1;
			UIView.Animate (0.7, 0, UIViewAnimationOptions.Repeat | UIViewAnimationOptions.Autoreverse, () =>
			{
				imgImage.Alpha = 0;
			}, () => { });

			UIView.Animate (0.15, 0, UIViewAnimationOptions.CurveEaseInOut, () =>
			 {
				 this.View.Layer.Opacity = 1;
			 }, () => { });
		}

		public void Hide ()
		{
			View.Layer.RemoveAllAnimations ();
			UIView.Animate (0.15, 0, UIViewAnimationOptions.CurveEaseInOut, () =>
			 {
				 this.View.Layer.Opacity = 0;
			 }, () => { });
		}
	}
}
