// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared.Models;
using Foundation;
using UIKit;

namespace Fanword.iOS
{
	public partial class ViewNotificationViewController : BaseViewController
	{
        public string NotificationTitle;
        public string NotificationMessage;
		public ViewNotificationViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);
            lblTitle.Text = NotificationTitle;
            lblContent.Text = NotificationMessage;

        }
	}

}
