// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Fanword.Poco.Models;
using Mobile.Extensions.iOS.Sources;
using System.Collections.Generic;
using Fanword.Shared;
using Mobile.Extensions.iOS.Extensions;
using System.Linq;

namespace Fanword.iOS
{
	public partial class TagProfileViewController : BaseViewController
	{
        public Post Post;
        CustomListSource<Profile> source;
        ProfileSearch result;
		public TagProfileViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            btnBack.TouchUpInside += (sender, e) =>
            {
                NavigationController.PopViewController(true);
            };   

            source = new CustomListSource<Profile>(new List<Profile>(), GetCell, (arg1, arg2) => 70);
            source.ItemClick += (sender, e) => 
            {
                if(result.TeamProfiles.Any(m => m.Id == e.Id))
                {
                    if (Post.Teams.Contains((e.Id)))
                    {
                        Post.Teams.Remove(e.Id);
                    }
                    else
                    {
                        Post.Teams.Add(e.Id);
                    }

                }
                else if(result.SchoolProfiles.Any(m => m.Id == e.Id))
                {
					if (Post.Schools.Contains((e.Id)))
					{
						Post.Schools.Remove(e.Id);
					}
					else
					{
						Post.Schools.Add(e.Id);
					}
                }
                else if(result.SportProfile.Any(m => m.Id == e.Id))
                {
					if (Post.Sports.Contains((e.Id)))
					{
						Post.Sports.Remove(e.Id);
					}
					else
					{
						Post.Sports.Add(e.Id);
					}
                }
                tvProfiles.ReloadData();
            };

            tvProfiles.Source = source;

            txtSearch.EditingChanged += (sender, e) => 
            {
                GetData();
            };

            btnNext.TouchUpInside += (sender, e) => 
            {
				var controller = Storyboard.InstantiateViewController<TagEventsViewController>();
				controller.Post = Post;
				NavigationController.PushViewController(controller, true);
            };
            LoadingScreen.Show();
            GetData();
        }

        void GetData()
        {
            var feedType = Post.ContentSourceId != null
                ? FeedType.ContentSource
                : Post.TeamId != null
                    ? FeedType.Team
                    : Post.SchoolId != null
                        ? FeedType.School
                        : FeedType.User;

            var apiTask = new ServiceApi().SearchProfiles(txtSearch.Text, Post.TeamId ?? Post.SchoolId, feedType);
            apiTask.HandleError(LoadingScreen);
            apiTask.OnSucess(response =>
            {
                if(response.Result.SearchText == txtSearch.Text)
                {
                    result = response.Result;
                    source.Items = response.Result.TeamProfiles.Union(response.Result.SchoolProfiles).Union(response.Result.SportProfile).ToList();
                    tvProfiles.ReloadData();
                    LoadingScreen.Hide();
                }
            });
        }


		public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath, Profile item)
		{
            var cell = tableView.DequeueReusableCell("ProfileSearchCell", indexPath) as ProfileSearchCell;
            cell.SetData(item, Post.Schools, Post.Teams, Post.Sports);
			cell.SelectionStyle = UITableViewCellSelectionStyle.None;
			return cell;
		}
	}
}
