// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Extensions;
using Fanword.Poco.Models;

namespace Fanword.iOS
{
	public partial class FeedViewController : BaseViewController
	{
		UIRefreshControl refreshControl;
        public string Id;
        public UIView HeaderView;
        public FeedType Type = FeedType.Main;
		public EventHandler<EventArgs> RefreshStarted;
		public FeedViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			tvFeed.Initialize(this, HeaderView, Id, Type);


			tvFeed.GetNewsFeedData (true);

			refreshControl = new UIRefreshControl ();
			tvFeed.AddSubview (refreshControl);
			tvFeed.customRefreshControl = refreshControl;
            refreshControl.AddTarget((sender, e) =>
            {
                tvFeed.GetNewsFeedData(true);
            }, UIControlEvent.ValueChanged);
			if (UIDevice.CurrentDevice.CheckSystemVersion (10, 0))
			{
				tvFeed.RefreshControl = refreshControl;
			}

            tvFeed.RefreshRequested += (sender, e) => 
            {
				RefreshStarted?.Invoke(this, EventArgs.Empty);
            };

            btnNewPost.TouchUpInside += (sender, e) => 
            {
                var controller = Storyboard.InstantiateViewController<EditPostViewController>();
                NavigationController.PushViewController(controller, true);
            };

		}

        public void HideAddPost()
        {
            btnNewPost.Hidden = true;
        }

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
            tvFeed.UpdateFeedItem(MainViewController.PostId);
            MainViewController.PostId = null;
		}
	}
}
