// This file has been autogenerated from a class added in the UI designer.

using System;
using Fanword.Shared.Helpers;
using Foundation;
using UIKit;
using Fanword.Poco.Models;

namespace Fanword.iOS
{
	public partial class TutorialViewController : UIViewController
	{
        public TutorialHelper Model;
        public Action Dismissed;
		public TutorialViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            lblTitle.Text = Model.Title;
            if(Model.Id == "Welcome")
            {
                var attributedTitle = new NSMutableAttributedString(Model.Title, lblTitle.Font, UIColor.Black, paragraphStyle: new NSMutableParagraphStyle() { Alignment = UITextAlignment.Center});
                attributedTitle.AddAttribute(UIStringAttributeKey.ForegroundColor,UIColor.FromRGB(249,95,6), new NSRange(8, Model.Title.Length - 8));
                lblTitle.AttributedText = attributedTitle;
            }


            var style = new NSMutableParagraphStyle();
            style.LineSpacing = 5;
            style.Alignment = UITextAlignment.Center;
            var attributed = new NSMutableAttributedString(Model.Subtitle);
            attributed.AddAttribute(UIStringAttributeKey.ParagraphStyle, style, new NSRange(0, Model.Subtitle.Length));
            lblSubtitle.AttributedText = attributed;

            imgImage.Image = UIImage.FromBundle(Model.Icon);

            btnOk.SetTitle(Model.ButtonText, UIControlState.Normal);

            btnOk.TouchUpInside += (sender, e) =>
            {
                DismissViewController(true,() => 
                {
                    Dismissed?.Invoke();
                });
            };

        }
	}
}
