// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Extensions;
using Fanword.Shared;

namespace Fanword.iOS
{
	public partial class FavoritesViewController : BaseViewController
	{
        FavoriteViewController teamsController;
        FavoriteViewController schoolsController;
        FavoriteViewController sportsController;
        FavoriteViewController contentSourcesController;
        FavoriteUsersViewController usersController;
        public string Page;
        public string SubPage;
		public FavoritesViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            btnBack.TouchUpInside += (sender, e) => 
            {
                NavigationController.PopViewController(true);
            };

			teamsController = Storyboard.InstantiateViewController<FavoriteViewController>();	
            AddChildViewController(teamsController);
			AddToScrollView(teamsController.View, 0);

			schoolsController = Storyboard.InstantiateViewController<FavoriteViewController>();
			AddChildViewController(schoolsController);
			AddToScrollView(schoolsController.View, 1);

			sportsController = Storyboard.InstantiateViewController<FavoriteViewController>();
			AddChildViewController(sportsController);
			AddToScrollView(sportsController.View, 2);

			contentSourcesController = Storyboard.InstantiateViewController<FavoriteViewController>();
			AddChildViewController(contentSourcesController);
			AddToScrollView(contentSourcesController.View, 3);

			usersController = Storyboard.InstantiateViewController<FavoriteUsersViewController>();
			AddChildViewController(usersController);
			AddToScrollView(usersController.View, 4);

			svScroller.ContentSize = new CoreGraphics.CGSize() { Width = UIScreen.MainScreen.Bounds.Width * 5 };

			svScroller.Scrolled += (sender, e) =>
			{
                lcIndicatorLeading.Constant = (svScroller.ContentOffset.X / UIScreen.MainScreen.Bounds.Width) * 90;
			};
            btnContentSources.TitleLabel.LineBreakMode = UILineBreakMode.WordWrap;
            btnContentSources.TitleLabel.TextAlignment = UITextAlignment.Center;
            btnContentSources.SetTitle("CONTENT\nSOURCES", UIControlState.Normal);

			GetData();

			btnTeams.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint(), true);
			};
			btnSchools.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width }, true);
			};
			btnSports.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 2 }, true);
			};
			btnContentSources.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 3 }, true);
			};
			btnUsers.TouchUpInside += (sender, e) =>
			{
				svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 4 }, true);
			};

            btnAdd.TouchUpInside += (sender, e) => 
            {
                var controller = Storyboard.InstantiateViewController<SearchViewContrroller>();
                NavigationController.PushViewController(controller, true);
            };

            if(Page == "Users")
            {
                svScroller.SetContentOffset(new CoreGraphics.CGPoint() { X = UIScreen.MainScreen.Bounds.Width * 4 }, true);
            }
        }

		void AddToScrollView(UIView view, int position)
		{
			svScroller.Add(view);
			var frame = view.Frame;
			frame.Y = 0;
			frame.X = UIScreen.MainScreen.Bounds.Width * position;
			frame.Height = UIScreen.MainScreen.Bounds.Height - 120;
			frame.Width = UIScreen.MainScreen.Bounds.Width;
			view.Frame = frame;
		}

		void GetData()
		{
            LoadingScreen.Show();
			var apiTask = new ServiceApi().Favorites();
			apiTask.HandleError(LoadingScreen);
			apiTask.OnSucess((response) =>
			{
				LoadingScreen.Hide();
				teamsController.SetData(response.Result.Teams);
				schoolsController.SetData(response.Result.Schools);
				sportsController.SetData(response.Result.Sports);
				contentSourcesController.SetData(response.Result.ContentSources);
                usersController.SetData(response.Result.Following, response.Result.Followers);
                if(SubPage == "Followers")
                {
                    usersController.ShowFollowers();
                }
			});
		}

		public override void ViewDidLayoutSubviews()
		{
			base.ViewDidLayoutSubviews();
			FixFrame(teamsController.View);
			FixFrame(schoolsController.View);
			FixFrame(sportsController.View);
			FixFrame(contentSourcesController.View);
			FixFrame(usersController.View);
		}

		void FixFrame(UIView view)
		{
			var f = view.Frame;
			f.Width = UIScreen.MainScreen.Bounds.Width;
            f.Height = UIScreen.MainScreen.Bounds.Height - 120;
			view.Frame = f;
		}
	
	}
}
