// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mobile.Extensions.iOS.Extensions;
using Fanword.Poco.Models;
using Plugin.Settings;
using Mobile.Extensions.Extensions;
using FFImageLoading;
using FFImageLoading.Transformations;
using Fanword.Shared;
using Fanword.Shared.Helpers;

namespace Fanword.iOS
{
	public partial class MyProfileViewController : BaseViewController
	{
        FeedViewController feedController;
		public MyProfileViewController (IntPtr handle) : base (handle)
		{
		}

		public override UIStatusBarStyle PreferredStatusBarStyle()
		{
			return UIStatusBarStyle.LightContent;
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			ShowHelpIfNecessary(TutorialHelper.Profiles);

			btnBack.TouchUpInside += (sender, e) => NavigationController.PopViewController(true);

            feedController = Storyboard.InstantiateViewController<FeedViewController>();
            feedController.HeaderView = vwHeader;
            feedController.Type = FeedType.MyProfile;
			feedController.RefreshStarted += (sender, e) => GetProfileData();
			AddChildViewController(feedController);
			View.Add(feedController.View);
			var f = feedController.View.Frame;
			f.X = 0;
			f.Y = 70;
			f.Width = UIScreen.MainScreen.Bounds.Width;
			f.Height = UIScreen.MainScreen.Bounds.Height-70;
			feedController.View.Frame = f;

            var user = CrossSettings.Current.GetValueOrDefaultJson<User>("User");
            lblName.Text = user.FirstName + " " + user.LastName;
            lblTitle.Text = lblName.Text;
            lblAthlete.Text = "";
            if(string.IsNullOrEmpty(lblAthlete.Text))
            {
                lblAthlete.Superview.Hidden = true;
            }
            if(!string.IsNullOrEmpty(user.ProfileUrl))
            {
                ImageService.Instance.LoadUrl(user.ProfileUrl).Retry(3, 300).Transform(new CircleTransformation()).Into(imgProfile);
            }

			lblAthlete.Superview.Hidden = string.IsNullOrEmpty(user.AthleteTeamId);
			lblAthlete.Text = user.AthleteSchool + " - " + user.AthleteSport;

            if (!user.AthleteVerified) {
                lblAthlete.Text = "";
                lblAthlete.Superview.Hidden = true;
            }

            lblFollowers.Superview.AddGestureRecognizer(new UITapGestureRecognizer(() =>
            {
                var controller = Storyboard.InstantiateViewController<FavoritesViewController>();
                controller.Page = "Users";
                controller.SubPage = "Followers";
                NavigationController.PushViewController(controller, true);
            }));

            lblFollowing.Superview.AddGestureRecognizer(new UITapGestureRecognizer(() =>
			{
				var controller = Storyboard.InstantiateViewController<FavoritesViewController>();
				//controller.Page = "Users";
				NavigationController.PushViewController(controller, true);
            }));

            feedController.HideAddPost();

            GetProfileData();
        }

        void GetProfileData()
        {
            var apiTask = new ServiceApi().GetMyProfileDetails();
            apiTask.HandleError(LoadingScreen);
            apiTask.OnSucess(response =>
            {
                lblPosts.Text = LargeValueHelper.GetString(response.Result.Posts);
                lblFollowing.Text = LargeValueHelper.GetString(response.Result.Following);
                lblFollowers.Text = LargeValueHelper.GetString(response.Result.Followers);
            });
        }
	}
}
