// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Fanword.iOS
{
	public partial class SchoolRankingsViewController : UIViewController
	{
        public string SchoolId;
		public SchoolRankingsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
